# Generated by Django 5.1.2 on 2024-11-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_priceproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceproduct',
            old_name='URLs_id',
            new_name='URLs',
        ),
    ]
